[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"