[build]
  command = "npm run build"
  publish = "out"
  functions = ".netlify/functions"

[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[headers]]
  for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"
  X-Frame-Options = "SAMEORIGIN"